package io.github.topher6835.mediacompare.location;

/** Stable bounded reason identities; volatile filesystem messages do not belong here. */
public enum ContinuityReason {
    EVIDENCE_MATCHED,
    PROFILE_UNSUPPORTED,
    PROBE_UNAVAILABLE,
    PROBE_UNCERTAIN,
    PROBE_ERROR,
    ANCHOR_LOCATION_MISMATCH,
    CONTEXT_VOLUME_UUID_MISMATCH,
    CONTEXT_INODE_MISMATCH,
    ANCHOR_DIRECTORY_MISMATCH,
    ANCHOR_SYMBOLIC_LINK_MISMATCH,
    SOURCE_CONTEXT_ID_MISMATCH,
    CONTEXT_REVISION_MISMATCH,
    SOURCE_LOCATION_REVISION_MISMATCH,
    SOURCE_ROOT_LOCATION_MISMATCH,
    SOURCE_ROOT_OUTSIDE_CONTEXT,
    SOURCE_ROOT_VOLUME_UUID_MISMATCH,
    SOURCE_ROOT_INODE_MISMATCH,
    SOURCE_ROOT_BIRTH_TIME_MISMATCH,
    SOURCE_ROOT_DIRECTORY_MISMATCH,
    SOURCE_ROOT_SYMBOLIC_LINK_MISMATCH
}
