spring.application.name=media-compare

spring.datasource.url=jdbc:sqlite:data/media-compare.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration