package io.github.topher6835.mediacompare.matching;

public enum CleanupPreflightReason {
    GROUP_CHANGED, KEEPER_UNAVAILABLE, CANDIDATE_SET_CHANGED,
    AUTHORITY_UNAVAILABLE, AUTHORITY_CHANGED, FILESYSTEM_CHANGED,
    UNSAFE_PATH, HASH_MISMATCH, IO_UNAVAILABLE
}
