package io.github.topher6835.mediacompare.scan.authority;

/** Bounded reasons that do not expose host filesystem error messages. */
public enum ScanAuthorityReason {
    ACCEPTED,
    SOURCE_UNBOUND,
    PROFILE_UNSUPPORTED,
    CONTEXT_NOT_CURRENT,
    AUTHORITY_UNAVAILABLE,
    AUTHORITY_UNCERTAIN,
    AUTHORITY_CHANGED,
    SOURCE_ID_CHANGED,
    SOURCE_REVISION_CHANGED,
    CONTEXT_REVISION_CHANGED,
    CONTEXT_ID_CHANGED,
    SOURCE_ROOT_CHANGED,
    FILE_OUTSIDE_SOURCE,
    FILE_OUTSIDE_CONTEXT,
    FILE_NOT_REGULAR,
    SYMBOLIC_LINK_BOUNDARY,
    CHILD_STORAGE_UNSUPPORTED,
    CHILD_STORAGE_UNCERTAIN,
    VOLUME_IDENTITY_MISMATCH,
    TRAVERSAL_ERROR,
    TRAVERSAL_CANCELLED,
    INACCESSIBLE_SUBTREE,
    TRAVERSAL_SCOPE_CHANGED
}
